version: '4'
services:
  moveit:
    image: moveit_refactor:latest
    container_name: moveit_refactor
    build:
      context: .
    ports:
      - "8082:8082"
    volumes:
      - ./web.py:/web.py

  redis:
    image: redis:7.2.4-bookworm
    container_name: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
