cities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Miami, FL",
    "Dallas, TX",
    "Houston, TX",
    "Philadelphia, PA",
    "Atlanta, GA",
    "Washington, DC",
    "Boston, MA",
    "Phoenix, AZ",
    "Detroit, MI",
    "San Francisco, CA",
    "Seattle, WA",
    "San Diego, CA",
    "Minneapolis, MN",
    "Tampa, FL",
    "Brooklyn, NY",
    "Denver, CO",
    "Queens, NY",
    "Baltimore, MD",
    "Las Vegas, NV",
    "St. Louis, MO",
    "Riverside, CA",
    "Portland, OR",
    "San Antonio, TX",
    "Sacramento, CA",
    "San Juan, PR",
    "San Jose, CA",
    "Orlando, FL",
    "Cleveland, OH",
    "Pittsburgh, PA",
    "Manhattan, NY",
    "Austin, TX",
    "Cincinnati, OH",
    "Indianapolis, IN",
    "Kansas City, MO",
    "Columbus, OH",
    "Charlotte, NC",
    "Virginia Beach, VA",
    "Bronx, NY",
    "Milwaukee, WI",
    "Providence, RI",
    "Jacksonville, FL",
    "Salt Lake City, UT",
    "Nashville, TN",
    "Raleigh, NC",
    "Memphis, TN",
    "Richmond, VA",
    "Louisville, KY",
    "New Orleans, LA",
    "Bridgeport, CT",
    "Oklahoma City, OK",
    "Buffalo, NY",
    "Hartford, CT",
    "Fort Worth, TX",
    "Tucson, AZ",
    "Honolulu, HI",
    "McAllen, TX",
    "El Paso, TX",
    "Omaha, NE",
    "Albuquerque, NM",
    "Birmingham, AL",
    "Sarasota, FL",
    "Dayton, OH",
    "Rochester, NY",
    "Fresno, CA",
    "Tulsa, OK",
    "Allentown, PA",
    "Concord, CA",
    "Cape Coral, FL",
    "Charleston, SC",
    "Colorado Springs, CO",
    "Springfield, MA",
    "Grand Rapids, MI",
    "Ogden, UT",
    "Columbia, SC",
    "Baton Rouge, LA",
    "Knoxville, TN",
    "Mission Viejo, CA",
    "Albany, NY",
    "Akron, OH",
    "New Haven, CT",
    "Provo, UT",
    "Bakersfield, CA",
    "Murrieta, CA",
    "Des Moines, IA",
    "Worcester, MA",
    "Mesa, AZ",
    "Toledo, OH",
    "Palm Bay, FL",
    "Staten Island, NY",
    "Wichita, KS",
    "Harrisburg, PA",
    "Long Beach, CA",
    "Little Rock, AR",
    "Madison, WI",
    "Greenville, SC",
    "Reno, NV",
    "Port St. Lucie, FL",
    "Lancaster, PA",
    "Spokane, WA",
    "Denton, TX",
    "Poughkeepsie, NY",
    "Oakland, CA",
    "Winston-Salem, NC",
    "Syracuse, NY",
    "Boise, ID",
    "Chattanooga, TN",
    "Augusta, GA",
    "Arlington, TX",
    "Stockton, CA",
    "Durham, NC",
    "Palm Coast, FL",
    "Scranton, PA",
    "Aurora, CO",
    "Oxnard, CA",
    "Modesto, CA",
    "Indio, CA",
    "Kissimmee, FL",
    "Youngstown, OH",
    "Pensacola, FL",
    "Lancaster, CA",
    "Anaheim, CA",
    "Fayetteville, AR",
    "Jackson, MS",
    "Victorville, CA",
    "Bonita Springs, FL",
    "Greensboro, NC",
    "Corpus Christi, TX",
    "Flint, MI",
    "Fayetteville, NC",
    "Santa Ana, CA",
    "Fort Wayne, IN",
    "Mobile, AL",
    "Lansing, MI",
    "Ann Arbor, MI",
    "Huntsville, AL",
    "Lexington, KY",
    "Santa Rosa, CA",
    "Antioch, CA",
    "Asheville, NC",
    "Henderson, NV",
    "St. Paul, MN",
    "Fort Collins, CO",
    "Lakeland, FL",
    "Springfield, MO",
    "The Woodlands, TX",
    "Shreveport, LA",
    "Trenton, NJ",
    "Plano, TX",
    "Round Lake Beach, IL",
    "South Bend, IN",
    "Savannah, GA",
    "Newark, NJ",
    "Davenport, IA",
    "Myrtle Beach, SC",
    "Lincoln, NE",
    "Rockford, IL",
    "Reading, PA",
    "Canton, OH",
    "Irvine, CA",
    "Eugene, OR",
    "Chula Vista, CA",
    "St. Petersburg, FL",
    "Salem, OR",
    "Lafayette, LA",
    "Laredo, TX",
    "Jersey City, NJ",
    "Santa Clarita, CA",
    "Aguadilla, PR",
    "Wilmington, NC",
    "Lubbock, TX",
    "Chandler, AZ",
    "Scottsdale, AZ",
    "Tallahassee, FL",
    "Montgomery, AL",
    "Peoria, IL",
    "Glendale, AZ",
    "Columbus, GA",
    "Anchorage, AK",
    "Gilbert, AZ",
    "North Las Vegas, NV",
    "Avondale, AZ",
    "McKinney, TX",
    "Norfolk, VA",
    "Chesapeake, VA",
    "Kennewick, WA",
    "Winter Haven, FL",
    "Irving, TX",
    "Garland, TX",
    "York, PA",
    "Concord, NC",
    "Arlington, VA",
    "Atlantic City, NJ",
    "Visalia, CA",
    "Fremont, CA",
    "Hialeah, FL",
    "Nashua, NH",
    "Killeen, TX",
    "Gulfport, MS",
    "Brownsville, TX",
    "Evansville, IN",
    "Appleton, WI",
    "Navarre, FL",
    "Bel Air South, MD",
    "Kalamazoo, MI",
    "Bremerton, WA",
    "Spring Valley, NV",
    "San Bernardino, CA",
    "Roanoke, VA",
    "Spartanburg, SC",
    "Tacoma, WA",
    "Enterprise, NV",
    "Green Bay, WI",
    "Portland, ME",
    "Thousand Oaks, CA",
    "Fontana, CA",
    "Hickory, NC",
    "Moreno Valley, CA",
    "Deltona, FL",
    "Fargo, ND",
    "Santa Barbara, CA",
    "College Station, TX",
    "Gainesville, FL",
    "Amarillo, TX",
    "Norwich, CT",
    "Olympia, WA",
    "Yonkers, NY",
    "Huntington Beach, CA",
    "Glendale, CA",
    "Aurora, IL",
    "Huntington, WV",
    "Sunrise Manor, NV",
    "North Port, FL",
    "Hagerstown, MD",
    "Grand Prairie, TX",
    "Overland Park, KS",
    "Paradise, NV",
    "Tempe, AZ",
    "Salinas, CA",
    "Erie, PA",
    "Cedar Rapids, IA",
    "Waterbury, CT",
    "Frisco, TX",
    "Waco, TX",
    "Gastonia, NC",
    "Clarksville, TN",
    "Vancouver, WA",
    "Lorain, OH",
    "Nampa, ID"
]
